language: r
r:
  - release
  - devel
cache: packages

r_github_packages:
  - mrcieu/gwasvcf

bioc_packages:
  - GenomicAlignments

script: true

warnings_are_errors: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
